### ISSUE TITLE
Downloading Mods with Space Or Underscore in ID breaks mod section

### ISSUE THREAD

**Issue by AJohnsonCHC** [mroote/factorio-server-manager#124]
Seems like downloading mods with a Space or an Underscore in their name breaks the mod section. It won't show what mods you have installed or let you add anymore.

Running in the latest docker container on Ubuntu 18.04 system.

Offending Mods: 
[Squeak Through](https://mods.factorio.com/mod/Squeak%20Through)
[Power Armor MK3](https://mods.factorio.com/mod/Power%20Armor%20MK3)
[Big_Brother](https://mods.factorio.com/mod/Big_Brother)

Probably more than this, just the ones I tried.

```
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mods_handler.go:230 +0x65e,
2018/10/20 03:22:46 download complete,
	/usr/lib/go/src/net/http/server.go:2795 +0x27b,
	/usr/lib/go/src/net/http/server.go:1830 +0x651,
created by net/http.(*Server).Serve,
net/http.(*conn).serve(0xc4203483c0, 0x8a5480, 0xc420028100),
	/usr/lib/go/src/net/http/server.go:2694 +0xbc,
net/http.serverHandler.ServeHTTP(0xc42009f040, 0x8a50c0, 0xc420453880, 0xc42060a200),
	/home/mitch/src/go/src/github.com/gorilla/mux/mux.go:114 +0xdc,
github.com/gorilla/mux.(*Router).ServeHTTP(0xc420632410, 0x8a50c0, 0xc420453880, 0xc42060af00),
	/usr/lib/go/src/net/http/server.go:1947 +0x44,
net/http.HandlerFunc.ServeHTTP(0xc42062c7e0, 0x8a50c0, 0xc420453880, 0xc42060af00),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/routes.go:116 +0x233,
main.AuthorizeHandler.func1(0x8a50c0, 0xc420453880, 0xc42060af00),
net/http.HandlerFunc.ServeHTTP(0x86d778, 0x8a50c0, 0xc420453880, 0xc42060af00),
main.ModPortalInstallHandler(0x8a50c0, 0xc420453880, 0xc42060af00),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:160 +0x588,
main.(*Mods).downloadMod(0xc4203d8690, 0xc4201ba5c0, 0x35, 0xc42031e04a, 0x1d, 0xc42031e070, 0x12, 0x0, 0x0),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_Mods.go:113 +0xcc,
main.(*Mods).createMod(0xc4203d8690, 0xc42031e070, 0x12, 0xc42031e04a, 0x1d, 0x8a1680, 0xc4202d24c0, 0xc420022840, 0x12),
goroutine 342 [running]:,
net/http.(*conn).serve.func1(0xc4203483c0),
panic(0x7cff00, 0xa72970),
	/usr/lib/go/src/runtime/panic.go:502 +0x229,
	/usr/lib/go/src/net/http/server.go:1726 +0xd0,
main.(*ModInfoList).listInstalledMods.func1(0xc42049b710, 0x30, 0x8a6820, 0xc420254820, 0x0, 0x0, 0x0, 0x0),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:80 +0x892,
	/usr/lib/go/src/path/filepath/path.go:357 +0x402,
path/filepath.walk(0xc42049b710, 0x30, 0x8a6820, 0xc420254820, 0xc420246e80, 0x0, 0x0),
path/filepath.walk(0xc420022840, 0x12, 0x8a6820, 0xc4201c1110, 0xc420246e80, 0x0, 0x10),
	/usr/lib/go/src/path/filepath/path.go:381 +0x2c2,
path/filepath.Walk(0xc420022840, 0x12, 0xc420246e80, 0xa7f560, 0xc42001fbf0),
	/usr/lib/go/src/path/filepath/path.go:403 +0x106,
main.(*ModInfoList).listInstalledMods(0xc4203d86b8, 0xc4207232f0, 0x30),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:50 +0x97,
main.(*ModInfoList).createMod(0xc4203d86b8, 0xc42031e070, 0x12, 0xc42031e04a, 0x1d, 0x8a1680, 0xc4202d24c0, 0x0, 0x0),
	/home/mitch/src/go/src/github.com/mroote/factorio-server-manager/src/mod_modInfo.go:205 +0x3fb,
2018/10/20 03:22:46 http: panic serving 172.17.0.16:47860: runtime error: index out of range,
 Status: 200 OK,
 StatusCode: 200,
2018/10/20 03:22:46 error finding basemodDependency. Using FactorioVersion...,
2018/10/20 03:22:31 error finding basemodDependency. Using FactorioVersion...,
2018/10/20 03:22:31 completed copying the response.Body
```

Mods also aren't added to modlist.json even though they are downloaded succesfully.

**Comment by AJohnsonCHC** [comment]
Actually looks like Big_Brother works fine, something else must have caused that crash. However it does appear that there is something keeping Squeak Through and Power Armor MK3 from installing.

**Comment by knoxfighter** [comment]
It has something to do with the way i get the baseModDependency, something that is also not working well in #123. As soon i have time (which problably will take a few weeks), i will look into that and make that system more relyable :)

**Comment by sunnythaper** [comment]
Also having this issue with Squeak Through. Starting to relearn how horrible Vanilla oil fields are again.

**Comment by sean-callahan** [comment]
After #126, this issue has been fixed.
All 3 example offending mods can now be downloaded without problems.
