### ISSUE TITLE
Unable to start 0.16.7 factorio server

### ISSUE THREAD

**Issue by Curtisdhi** [mroote/factorio-server-manager#88]
Seems like rcon-pass is no longer an option?

```
2017/12/21 23:54:25 Starting server with command:  /factorioServers/factorio/bin/x64/factorio [--port 34197 --server-settings /factorioServers/factorio/config/server-settings.json --rcon-port 43081 --rcon-pass factorio_rcon --start-server /factorioServers/factorio/saves/map.zip]
2017/12/21 23:54:25 Factorio Server: Option ‘rcon-pass’ does not exist
2017/12/21 23:54:25 Factorio Server:
2017/12/21 23:54:25 Factorio Server: Usage:
2017/12/21 23:54:25 Factorio process exited with error: exit status 1
2017/12/21 23:54:25 Error starting Factorio server: exit status 1
panic: runtime error: index out of range

goroutine 46 [running]:
panic(0x7901a0, 0xc4200100f0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
main.(*FactorioServer).parseRunningCommand(0xc42007a280, 0x998400, 0xc4200fa5b0, 0xc4205e7080, 0x8)
        /home/mitch/prog/go/src/github.com/majormjr/factorio-server-manager/src/factorio_server.go:173 +0x5af
created by main.(*FactorioServer).Run
        /home/mitch/prog/go/src/github.com/majormjr/factorio-server-manager/src/factorio_server.go:141 +0x9d9
```

**Comment by mroote** [comment]
Thanks for the bug report @Curtisdhi.  Luckily @tmathmeyer just submitted a fix to update this flag.  The fix is included in the new release here: https://github.com/mroote/factorio-server-manager/releases/tag/0.6.1

**Comment by Curtisdhi** [comment]
Sweet. Thanks!
